-- Create 30 teams automatically for the super admin
INSERT INTO public.groups (name, description) VALUES
('Team 1', 'Team 1 - Development Group'),
('Team 2', 'Team 2 - Development Group'),
('Team 3', 'Team 3 - Development Group'),
('Team 4', 'Team 4 - Development Group'),
('Team 5', 'Team 5 - Development Group'),
('Team 6', 'Team 6 - Development Group'),
('Team 7', 'Team 7 - Development Group'),
('Team 8', 'Team 8 - Development Group'),
('Team 9', 'Team 9 - Development Group'),
('Team 10', 'Team 10 - Development Group'),
('Team 11', 'Team 11 - Development Group'),
('Team 12', 'Team 12 - Development Group'),
('Team 13', 'Team 13 - Development Group'),
('Team 14', 'Team 14 - Development Group'),
('Team 15', 'Team 15 - Development Group'),
('Team 16', 'Team 16 - Development Group'),
('Team 17', 'Team 17 - Development Group'),
('Team 18', 'Team 18 - Development Group'),
('Team 19', 'Team 19 - Development Group'),
('Team 20', 'Team 20 - Development Group'),
('Team 21', 'Team 21 - Development Group'),
('Team 22', 'Team 22 - Development Group'),
('Team 23', 'Team 23 - Development Group'),
('Team 24', 'Team 24 - Development Group'),
('Team 25', 'Team 25 - Development Group'),
('Team 26', 'Team 26 - Development Group'),
('Team 27', 'Team 27 - Development Group'),
('Team 28', 'Team 28 - Development Group'),
('Team 29', 'Team 29 - Development Group'),
('Team 30', 'Team 30 - Development Group')
ON CONFLICT (name) DO NOTHING;