
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpzhfcyowotsrymrxxpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wemhmY3lvd290c3J5bXJ4eHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTQ4OTMsImV4cCI6MjA2OTM3MDg5M30.IUQdV3EwNLqT7gPtcGDC07ct_h9i_NyKLte1ZWVNdIg";

console.log("Supabase client initializing...");
console.log("SUPABASE_URL:", SUPABASE_URL);
console.log("SUPABASE_PUBLISHABLE_KEY exists:", !!SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

console.log("Supabase client created successfully");
